# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "codespace-loonpn-turbo-train-p4j6v57pr5ghrqp7" ]
  pull_request:
    branches: [ "codespace-loonpn-turbo-train-p4j6v57pr5ghrqp7" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build for arm
      run: GOARCH=arm go build -ldflags="-w -s" -o ./build/tvbox-IPTV-proxy ./main.go

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: main-builds
        path: ./build/
